### ISSUE TITLE
Could not found module './build/Release/native' from 'index.js'

### ISSUE THREAD

**Issue by theofilis** [chad3814/node-hashtable#39]
I install version 2.0.2 and on runtime I have this error:

Cannot find module './build/Release/native' from 'index.js'

      at Resolver.resolveModule (../../../../../../.nvm/v6.10.3/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:181:17)
      at Object.<anonymous> (node_modules/hfc/node_modules/hashtable/index.js:1:139)

I have a workaround by change first line of `index.js` from `var HashTable = require('./build/Release/native').HashTable;` to `var HashTable = require('./build/Release/native.node').HashTable;`

I am currently working on Ubuntu 16.04 OS.

**Comment by starspoint** [comment]
This is not working to me.
I am running this module in Centos

**Comment by rddill-IBM** [comment]
Running Node V6 LTS. Had to change index.js from: 
```
var HashTable = require('./build/Release/native').HashTable;
```
to:
```
var HashTable = require('./build/Release/native.node').HashTable;
```
App now loads successfully.

**Comment by theofilis** [comment]
@rddill-IBM I had made the same change and work great on Node V6 and V7

**Comment by starspoint** [comment]
Found that my issue was on multiple version of Node installed in /bin and also /usr/local/bin. 
Beside I was running the module under /usr/local/bin. Hence the node-gyp does not run properly and module build failed. It took me so long to find this silly mistake.

**Comment by theofilis** [comment]
With this library me to I had very difficult time until I figure out how I could solve some issues. As an example, It was impossible to compile the official version of it on latest OSX.
